from _typeshed import Incomplete
from collections.abc import Generator

def get_symlinks(base_folder) -> Generator[Incomplete, None, None]: ...
def _path_inside(base, folder): ...
def absolute_to_relative_symlinks(conanfile, base_folder) -> None: ...
def remove_external_symlinks(conanfile, base_folder: Incomplete | None = ...) -> None: ...
def remove_broken_symlinks(conanfile, base_folder: Incomplete | None = ...) -> None: ...
