def architecture_flag(settings): ...
def libcxx_flags(conanfile): ...
def build_type_link_flags(settings): ...
def build_type_flags(settings): ...
def use_win_mingw(conanfile): ...
def cppstd_flag(settings): ...
def _cppstd_visualstudio(visual_version, cppstd): ...
def _cppstd_msvc(visual_version, cppstd): ...
def _cppstd_apple_clang(clang_version, cppstd): ...
def _cppstd_clang(clang_version, cppstd): ...
def _cppstd_gcc(gcc_version, cppstd): ...
def _cppstd_intel_common(intel_version, cppstd, vgnu98, vgnu0x): ...
def _cppstd_intel_gcc(intel_version, cppstd): ...
def _cppstd_intel_visualstudio(intel_version, cppstd): ...
def _cppstd_mcst_lcc(mcst_lcc_version, cppstd): ...
def _cppstd_intel_cc(_, cppstd): ...
