

'''
	python3 STATUS.py "FOOD/USDA/FORM_1/STATUS/STATUS_1.py"
'''

import CYTE.FOOD.USDA.EXAMPLES as USDA_EXAMPLES

def CHECK_1 ():
	EXAMPLE = USDA_EXAMPLES.RETRIEVE ("BRANDED/BEET_JUICE_2642759.JSON")

	import CYTE.FOOD.USDA.FORM_1 as FORM_1
	RETURNS = FORM_1.MAKE (
		USDA_FOOD_DATA = EXAMPLE
	)
	
	FORM_1 = RETURNS ["FORM"]
	NOTES = RETURNS ["NOTES"]
	
	assert (FORM_1 ["PRODUCT"]["NAME"] == "UP BEET COLD PRESSED JUICE, UP BEET")

	assert (len (NOTES) == 0)

	return;
	
	
CHECKS = {
	"BEET JUICE 2642759": CHECK_1
}