from _typeshed import Incomplete
from conan.tools.build import build_jobs as build_jobs
from conan.tools.files import chdir as chdir
from conan.tools.files.files import load_toolchain_args as load_toolchain_args
from conan.tools.microsoft import unix_path as unix_path

class Autotools:
    _conanfile: Incomplete
    _configure_args: Incomplete
    _make_args: Incomplete
    _autoreconf_args: Incomplete
    def __init__(self, conanfile, namespace: Incomplete | None = ...) -> None: ...
    def configure(self, build_script_folder: Incomplete | None = ..., args: Incomplete | None = ...) -> None: ...
    def make(self, target: Incomplete | None = ..., args: Incomplete | None = ...) -> None: ...
    def install(self, args: Incomplete | None = ..., target: str = ...) -> None: ...
    def autoreconf(self, args: Incomplete | None = ...) -> None: ...
    def _use_win_mingw(self): ...
