from _typeshed import Incomplete
from conan.tools.env import Environment as Environment

class PkgConfig:
    _conanfile: Incomplete
    _library: Incomplete
    _info: Incomplete
    _pkg_config_path: Incomplete
    _variables: Incomplete
    def __init__(self, conanfile, library, pkg_config_path: Incomplete | None = ...) -> None: ...
    def _parse_output(self, option): ...
    def _get_option(self, option): ...
    @property
    def includedirs(self): ...
    @property
    def cflags(self): ...
    @property
    def defines(self): ...
    @property
    def libdirs(self): ...
    @property
    def libs(self): ...
    @property
    def linkflags(self): ...
    @property
    def provides(self): ...
    @property
    def version(self): ...
    @property
    def variables(self): ...
    def fill_cpp_info(self, cpp_info, is_system: bool = ..., system_libs: Incomplete | None = ...) -> None: ...
