from _typeshed import Incomplete
from conan.tools.scm.git import Git as Git

class _VersionItem:
    _v: Incomplete
    def __init__(self, item) -> None: ...
    @property
    def value(self): ...
    def __str__(self): ...
    def __add__(self, other): ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    def __lt__(self, other): ...

class Version:
    _value: Incomplete
    _build: Incomplete
    _pre: Incomplete
    _items: Incomplete
    _nonzero_items: Incomplete
    def __init__(self, value) -> None: ...
    def bump(self, index): ...
    def upper_bound(self, index): ...
    @property
    def pre(self): ...
    @property
    def build(self): ...
    @property
    def main(self): ...
    @property
    def major(self): ...
    @property
    def minor(self): ...
    @property
    def patch(self): ...
    @property
    def micro(self): ...
    def __str__(self): ...
    def __repr__(self): ...
    def __eq__(self, other): ...
    def __hash__(self): ...
    def __lt__(self, other): ...
