# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sdk/stream/aggregates_spot_exchange_rate_v1/request.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9sdk/stream/aggregates_spot_exchange_rate_v1/request.proto\x12\x08kaikosdk\"]\n)StreamAggregatesSpotExchangeRateRequestV1\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x11\n\taggregate\x18\x02 \x01(\t\x12\x0f\n\x07sources\x18\x03 \x01(\x08\x42\xd4\x01\n5com.kaiko.sdk.stream.aggregates_spot_exchange_rate_v1P\x01Zjgithub.com/kaikodata/kaiko-go-sdk/stream/aggregates_spot_exchange_rate_v1;aggregates_spot_exchange_rate_v1\xaa\x02,KaikoSdk.Stream.AggregatesSpotExchangeRateV1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sdk.stream.aggregates_spot_exchange_rate_v1.request_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n5com.kaiko.sdk.stream.aggregates_spot_exchange_rate_v1P\001Zjgithub.com/kaikodata/kaiko-go-sdk/stream/aggregates_spot_exchange_rate_v1;aggregates_spot_exchange_rate_v1\252\002,KaikoSdk.Stream.AggregatesSpotExchangeRateV1'
  _STREAMAGGREGATESSPOTEXCHANGERATEREQUESTV1._serialized_start=71
  _STREAMAGGREGATESSPOTEXCHANGERATEREQUESTV1._serialized_end=164
# @@protoc_insertion_point(module_scope)
