# coding: utf-8

"""
    Aries Cloud Agent

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0.9.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re
from typing import Any, ClassVar, Dict, List, Optional

from pydantic import BaseModel, Field, StrictStr, field_validator
from typing_extensions import Annotated

from aries_cloudcontroller.util import DEFAULT_PYDANTIC_MODEL_CONFIG
from aries_cloudcontroller.util.regex_patterns import BASE58_PATTERN

try:
    from typing import Self
except ImportError:
    from typing_extensions import Self


class IndyPresAttrSpec(BaseModel):
    """
    IndyPresAttrSpec
    """

    cred_def_id: Optional[Annotated[str, Field(strict=True)]] = None
    mime_type: Optional[StrictStr] = Field(
        default=None, description="MIME type (default null)", alias="mime-type"
    )
    name: StrictStr = Field(description="Attribute name")
    referent: Optional[StrictStr] = Field(
        default=None, description="Credential referent"
    )
    value: Optional[StrictStr] = Field(default=None, description="Attribute value")
    __properties: ClassVar[List[str]] = [
        "cred_def_id",
        "mime-type",
        "name",
        "referent",
        "value",
    ]

    @field_validator("cred_def_id")
    def cred_def_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        pattern = rf"^({BASE58_PATTERN}{{21,22}}):3:CL:(([1-9][0-9]*)|({BASE58_PATTERN}{{21,22}}2:.+:[0-9.]+)):(.+)?$"
        if not re.match(pattern, value):
            raise ValueError(rf"must validate the regular expression {pattern}")

        return value

    model_config = DEFAULT_PYDANTIC_MODEL_CONFIG

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of IndyPresAttrSpec from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={},
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Self:
        """Create an instance of IndyPresAttrSpec from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "cred_def_id": obj.get("cred_def_id"),
                "mime-type": obj.get("mime-type"),
                "name": obj.get("name"),
                "referent": obj.get("referent"),
                "value": obj.get("value"),
            }
        )
        return _obj
