# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.


import collections

from sys import version_info as _version_info
if _version_info < (3, 7, 0):
    raise RuntimeError("Python 3.7 or later required")

from . import _ITKCommonPython


from . import _ITKLabelMapPython



from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _itkBinaryShapeKeepNObjectsImageFilterPython
else:
    import _itkBinaryShapeKeepNObjectsImageFilterPython

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

_swig_new_instance_method = _itkBinaryShapeKeepNObjectsImageFilterPython.SWIG_PyInstanceMethod_New
_swig_new_static_method = _itkBinaryShapeKeepNObjectsImageFilterPython.SWIG_PyStaticMethod_New

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


import collections.abc
import itk.ITKCommonBasePython
import itk.itkMatrixPython
import itk.itkPointPython
import itk.itkFixedArrayPython
import itk.pyBasePython
import itk.itkVectorPython
import itk.vnl_vectorPython
import itk.vnl_matrixPython
import itk.stdcomplexPython
import itk.vnl_vector_refPython
import itk.itkCovariantVectorPython
import itk.vnl_matrix_fixedPython
import itk.itkImageToImageFilterAPython
import itk.itkVectorImagePython
import itk.itkImagePython
import itk.itkSymmetricSecondRankTensorPython
import itk.itkRGBAPixelPython
import itk.itkIndexPython
import itk.itkOffsetPython
import itk.itkSizePython
import itk.itkImageRegionPython
import itk.itkRGBPixelPython
import itk.itkVariableLengthVectorPython
import itk.itkImageSourcePython
import itk.itkPhasedArray3DSpecialCoordinatesImagePython
import itk.itkImageSourceCommonPython
import itk.itkImageToImageFilterCommonPython

def itkBinaryShapeKeepNObjectsImageFilterISS2_New():
    return itkBinaryShapeKeepNObjectsImageFilterISS2.New()

class itkBinaryShapeKeepNObjectsImageFilterISS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS2ISS2):
    r"""Proxy of C++ itkBinaryShapeKeepNObjectsImageFilterISS2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS2___New_orig__)
    Clone = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS2_Clone)
    SetFullyConnected = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS2_SetFullyConnected)
    GetFullyConnected = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS2_GetFullyConnected)
    FullyConnectedOn = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS2_FullyConnectedOn)
    FullyConnectedOff = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS2_FullyConnectedOff)
    InputEqualityComparableCheck = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS2_InputEqualityComparableCheck
    
    IntConvertibleToInputCheck = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS2_IntConvertibleToInputCheck
    
    InputOStreamWritableCheck = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS2_InputOStreamWritableCheck
    
    SetBackgroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS2_SetBackgroundValue)
    GetBackgroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS2_GetBackgroundValue)
    SetForegroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS2_SetForegroundValue)
    GetForegroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS2_GetForegroundValue)
    GetNumberOfObjects = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS2_GetNumberOfObjects)
    SetNumberOfObjects = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS2_SetNumberOfObjects)
    GetReverseOrdering = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS2_GetReverseOrdering)
    SetReverseOrdering = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS2_SetReverseOrdering)
    ReverseOrderingOn = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS2_ReverseOrderingOn)
    ReverseOrderingOff = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS2_ReverseOrderingOff)
    GetAttribute = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS2_GetAttribute)
    SetAttribute = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS2_SetAttribute)
    __swig_destroy__ = _itkBinaryShapeKeepNObjectsImageFilterPython.delete_itkBinaryShapeKeepNObjectsImageFilterISS2
    cast = _swig_new_static_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS2_cast)

    def New(*args, **kargs):
        """New() -> itkBinaryShapeKeepNObjectsImageFilterISS2

        Create a new object of the class itkBinaryShapeKeepNObjectsImageFilterISS2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkBinaryShapeKeepNObjectsImageFilterISS2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkBinaryShapeKeepNObjectsImageFilterISS2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkBinaryShapeKeepNObjectsImageFilterISS2.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkBinaryShapeKeepNObjectsImageFilterISS2 in _itkBinaryShapeKeepNObjectsImageFilterPython:
_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS2_swigregister(itkBinaryShapeKeepNObjectsImageFilterISS2)
itkBinaryShapeKeepNObjectsImageFilterISS2___New_orig__ = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS2___New_orig__
itkBinaryShapeKeepNObjectsImageFilterISS2_cast = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS2_cast


def itkBinaryShapeKeepNObjectsImageFilterISS3_New():
    return itkBinaryShapeKeepNObjectsImageFilterISS3.New()

class itkBinaryShapeKeepNObjectsImageFilterISS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS3ISS3):
    r"""Proxy of C++ itkBinaryShapeKeepNObjectsImageFilterISS3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS3___New_orig__)
    Clone = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS3_Clone)
    SetFullyConnected = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS3_SetFullyConnected)
    GetFullyConnected = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS3_GetFullyConnected)
    FullyConnectedOn = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS3_FullyConnectedOn)
    FullyConnectedOff = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS3_FullyConnectedOff)
    InputEqualityComparableCheck = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS3_InputEqualityComparableCheck
    
    IntConvertibleToInputCheck = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS3_IntConvertibleToInputCheck
    
    InputOStreamWritableCheck = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS3_InputOStreamWritableCheck
    
    SetBackgroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS3_SetBackgroundValue)
    GetBackgroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS3_GetBackgroundValue)
    SetForegroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS3_SetForegroundValue)
    GetForegroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS3_GetForegroundValue)
    GetNumberOfObjects = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS3_GetNumberOfObjects)
    SetNumberOfObjects = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS3_SetNumberOfObjects)
    GetReverseOrdering = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS3_GetReverseOrdering)
    SetReverseOrdering = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS3_SetReverseOrdering)
    ReverseOrderingOn = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS3_ReverseOrderingOn)
    ReverseOrderingOff = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS3_ReverseOrderingOff)
    GetAttribute = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS3_GetAttribute)
    SetAttribute = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS3_SetAttribute)
    __swig_destroy__ = _itkBinaryShapeKeepNObjectsImageFilterPython.delete_itkBinaryShapeKeepNObjectsImageFilterISS3
    cast = _swig_new_static_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS3_cast)

    def New(*args, **kargs):
        """New() -> itkBinaryShapeKeepNObjectsImageFilterISS3

        Create a new object of the class itkBinaryShapeKeepNObjectsImageFilterISS3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkBinaryShapeKeepNObjectsImageFilterISS3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkBinaryShapeKeepNObjectsImageFilterISS3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkBinaryShapeKeepNObjectsImageFilterISS3.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkBinaryShapeKeepNObjectsImageFilterISS3 in _itkBinaryShapeKeepNObjectsImageFilterPython:
_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS3_swigregister(itkBinaryShapeKeepNObjectsImageFilterISS3)
itkBinaryShapeKeepNObjectsImageFilterISS3___New_orig__ = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS3___New_orig__
itkBinaryShapeKeepNObjectsImageFilterISS3_cast = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS3_cast


def itkBinaryShapeKeepNObjectsImageFilterISS4_New():
    return itkBinaryShapeKeepNObjectsImageFilterISS4.New()

class itkBinaryShapeKeepNObjectsImageFilterISS4(itk.itkImageToImageFilterAPython.itkImageToImageFilterISS4ISS4):
    r"""Proxy of C++ itkBinaryShapeKeepNObjectsImageFilterISS4 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS4___New_orig__)
    Clone = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS4_Clone)
    SetFullyConnected = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS4_SetFullyConnected)
    GetFullyConnected = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS4_GetFullyConnected)
    FullyConnectedOn = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS4_FullyConnectedOn)
    FullyConnectedOff = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS4_FullyConnectedOff)
    InputEqualityComparableCheck = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS4_InputEqualityComparableCheck
    
    IntConvertibleToInputCheck = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS4_IntConvertibleToInputCheck
    
    InputOStreamWritableCheck = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS4_InputOStreamWritableCheck
    
    SetBackgroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS4_SetBackgroundValue)
    GetBackgroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS4_GetBackgroundValue)
    SetForegroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS4_SetForegroundValue)
    GetForegroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS4_GetForegroundValue)
    GetNumberOfObjects = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS4_GetNumberOfObjects)
    SetNumberOfObjects = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS4_SetNumberOfObjects)
    GetReverseOrdering = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS4_GetReverseOrdering)
    SetReverseOrdering = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS4_SetReverseOrdering)
    ReverseOrderingOn = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS4_ReverseOrderingOn)
    ReverseOrderingOff = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS4_ReverseOrderingOff)
    GetAttribute = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS4_GetAttribute)
    SetAttribute = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS4_SetAttribute)
    __swig_destroy__ = _itkBinaryShapeKeepNObjectsImageFilterPython.delete_itkBinaryShapeKeepNObjectsImageFilterISS4
    cast = _swig_new_static_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS4_cast)

    def New(*args, **kargs):
        """New() -> itkBinaryShapeKeepNObjectsImageFilterISS4

        Create a new object of the class itkBinaryShapeKeepNObjectsImageFilterISS4 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkBinaryShapeKeepNObjectsImageFilterISS4.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkBinaryShapeKeepNObjectsImageFilterISS4.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkBinaryShapeKeepNObjectsImageFilterISS4.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkBinaryShapeKeepNObjectsImageFilterISS4 in _itkBinaryShapeKeepNObjectsImageFilterPython:
_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS4_swigregister(itkBinaryShapeKeepNObjectsImageFilterISS4)
itkBinaryShapeKeepNObjectsImageFilterISS4___New_orig__ = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS4___New_orig__
itkBinaryShapeKeepNObjectsImageFilterISS4_cast = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterISS4_cast


def itkBinaryShapeKeepNObjectsImageFilterIUC2_New():
    return itkBinaryShapeKeepNObjectsImageFilterIUC2.New()

class itkBinaryShapeKeepNObjectsImageFilterIUC2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC2IUC2):
    r"""Proxy of C++ itkBinaryShapeKeepNObjectsImageFilterIUC2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC2___New_orig__)
    Clone = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC2_Clone)
    SetFullyConnected = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC2_SetFullyConnected)
    GetFullyConnected = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC2_GetFullyConnected)
    FullyConnectedOn = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC2_FullyConnectedOn)
    FullyConnectedOff = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC2_FullyConnectedOff)
    InputEqualityComparableCheck = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC2_InputEqualityComparableCheck
    
    IntConvertibleToInputCheck = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC2_IntConvertibleToInputCheck
    
    InputOStreamWritableCheck = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC2_InputOStreamWritableCheck
    
    SetBackgroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC2_SetBackgroundValue)
    GetBackgroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC2_GetBackgroundValue)
    SetForegroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC2_SetForegroundValue)
    GetForegroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC2_GetForegroundValue)
    GetNumberOfObjects = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC2_GetNumberOfObjects)
    SetNumberOfObjects = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC2_SetNumberOfObjects)
    GetReverseOrdering = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC2_GetReverseOrdering)
    SetReverseOrdering = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC2_SetReverseOrdering)
    ReverseOrderingOn = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC2_ReverseOrderingOn)
    ReverseOrderingOff = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC2_ReverseOrderingOff)
    GetAttribute = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC2_GetAttribute)
    SetAttribute = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC2_SetAttribute)
    __swig_destroy__ = _itkBinaryShapeKeepNObjectsImageFilterPython.delete_itkBinaryShapeKeepNObjectsImageFilterIUC2
    cast = _swig_new_static_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC2_cast)

    def New(*args, **kargs):
        """New() -> itkBinaryShapeKeepNObjectsImageFilterIUC2

        Create a new object of the class itkBinaryShapeKeepNObjectsImageFilterIUC2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkBinaryShapeKeepNObjectsImageFilterIUC2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkBinaryShapeKeepNObjectsImageFilterIUC2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkBinaryShapeKeepNObjectsImageFilterIUC2.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkBinaryShapeKeepNObjectsImageFilterIUC2 in _itkBinaryShapeKeepNObjectsImageFilterPython:
_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC2_swigregister(itkBinaryShapeKeepNObjectsImageFilterIUC2)
itkBinaryShapeKeepNObjectsImageFilterIUC2___New_orig__ = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC2___New_orig__
itkBinaryShapeKeepNObjectsImageFilterIUC2_cast = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC2_cast


def itkBinaryShapeKeepNObjectsImageFilterIUC3_New():
    return itkBinaryShapeKeepNObjectsImageFilterIUC3.New()

class itkBinaryShapeKeepNObjectsImageFilterIUC3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC3IUC3):
    r"""Proxy of C++ itkBinaryShapeKeepNObjectsImageFilterIUC3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC3___New_orig__)
    Clone = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC3_Clone)
    SetFullyConnected = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC3_SetFullyConnected)
    GetFullyConnected = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC3_GetFullyConnected)
    FullyConnectedOn = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC3_FullyConnectedOn)
    FullyConnectedOff = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC3_FullyConnectedOff)
    InputEqualityComparableCheck = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC3_InputEqualityComparableCheck
    
    IntConvertibleToInputCheck = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC3_IntConvertibleToInputCheck
    
    InputOStreamWritableCheck = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC3_InputOStreamWritableCheck
    
    SetBackgroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC3_SetBackgroundValue)
    GetBackgroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC3_GetBackgroundValue)
    SetForegroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC3_SetForegroundValue)
    GetForegroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC3_GetForegroundValue)
    GetNumberOfObjects = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC3_GetNumberOfObjects)
    SetNumberOfObjects = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC3_SetNumberOfObjects)
    GetReverseOrdering = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC3_GetReverseOrdering)
    SetReverseOrdering = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC3_SetReverseOrdering)
    ReverseOrderingOn = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC3_ReverseOrderingOn)
    ReverseOrderingOff = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC3_ReverseOrderingOff)
    GetAttribute = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC3_GetAttribute)
    SetAttribute = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC3_SetAttribute)
    __swig_destroy__ = _itkBinaryShapeKeepNObjectsImageFilterPython.delete_itkBinaryShapeKeepNObjectsImageFilterIUC3
    cast = _swig_new_static_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC3_cast)

    def New(*args, **kargs):
        """New() -> itkBinaryShapeKeepNObjectsImageFilterIUC3

        Create a new object of the class itkBinaryShapeKeepNObjectsImageFilterIUC3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkBinaryShapeKeepNObjectsImageFilterIUC3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkBinaryShapeKeepNObjectsImageFilterIUC3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkBinaryShapeKeepNObjectsImageFilterIUC3.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkBinaryShapeKeepNObjectsImageFilterIUC3 in _itkBinaryShapeKeepNObjectsImageFilterPython:
_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC3_swigregister(itkBinaryShapeKeepNObjectsImageFilterIUC3)
itkBinaryShapeKeepNObjectsImageFilterIUC3___New_orig__ = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC3___New_orig__
itkBinaryShapeKeepNObjectsImageFilterIUC3_cast = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC3_cast


def itkBinaryShapeKeepNObjectsImageFilterIUC4_New():
    return itkBinaryShapeKeepNObjectsImageFilterIUC4.New()

class itkBinaryShapeKeepNObjectsImageFilterIUC4(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUC4IUC4):
    r"""Proxy of C++ itkBinaryShapeKeepNObjectsImageFilterIUC4 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC4___New_orig__)
    Clone = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC4_Clone)
    SetFullyConnected = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC4_SetFullyConnected)
    GetFullyConnected = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC4_GetFullyConnected)
    FullyConnectedOn = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC4_FullyConnectedOn)
    FullyConnectedOff = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC4_FullyConnectedOff)
    InputEqualityComparableCheck = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC4_InputEqualityComparableCheck
    
    IntConvertibleToInputCheck = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC4_IntConvertibleToInputCheck
    
    InputOStreamWritableCheck = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC4_InputOStreamWritableCheck
    
    SetBackgroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC4_SetBackgroundValue)
    GetBackgroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC4_GetBackgroundValue)
    SetForegroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC4_SetForegroundValue)
    GetForegroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC4_GetForegroundValue)
    GetNumberOfObjects = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC4_GetNumberOfObjects)
    SetNumberOfObjects = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC4_SetNumberOfObjects)
    GetReverseOrdering = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC4_GetReverseOrdering)
    SetReverseOrdering = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC4_SetReverseOrdering)
    ReverseOrderingOn = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC4_ReverseOrderingOn)
    ReverseOrderingOff = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC4_ReverseOrderingOff)
    GetAttribute = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC4_GetAttribute)
    SetAttribute = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC4_SetAttribute)
    __swig_destroy__ = _itkBinaryShapeKeepNObjectsImageFilterPython.delete_itkBinaryShapeKeepNObjectsImageFilterIUC4
    cast = _swig_new_static_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC4_cast)

    def New(*args, **kargs):
        """New() -> itkBinaryShapeKeepNObjectsImageFilterIUC4

        Create a new object of the class itkBinaryShapeKeepNObjectsImageFilterIUC4 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkBinaryShapeKeepNObjectsImageFilterIUC4.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkBinaryShapeKeepNObjectsImageFilterIUC4.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkBinaryShapeKeepNObjectsImageFilterIUC4.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkBinaryShapeKeepNObjectsImageFilterIUC4 in _itkBinaryShapeKeepNObjectsImageFilterPython:
_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC4_swigregister(itkBinaryShapeKeepNObjectsImageFilterIUC4)
itkBinaryShapeKeepNObjectsImageFilterIUC4___New_orig__ = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC4___New_orig__
itkBinaryShapeKeepNObjectsImageFilterIUC4_cast = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUC4_cast


def itkBinaryShapeKeepNObjectsImageFilterIUS2_New():
    return itkBinaryShapeKeepNObjectsImageFilterIUS2.New()

class itkBinaryShapeKeepNObjectsImageFilterIUS2(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUS2IUS2):
    r"""Proxy of C++ itkBinaryShapeKeepNObjectsImageFilterIUS2 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS2___New_orig__)
    Clone = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS2_Clone)
    SetFullyConnected = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS2_SetFullyConnected)
    GetFullyConnected = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS2_GetFullyConnected)
    FullyConnectedOn = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS2_FullyConnectedOn)
    FullyConnectedOff = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS2_FullyConnectedOff)
    InputEqualityComparableCheck = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS2_InputEqualityComparableCheck
    
    IntConvertibleToInputCheck = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS2_IntConvertibleToInputCheck
    
    InputOStreamWritableCheck = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS2_InputOStreamWritableCheck
    
    SetBackgroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS2_SetBackgroundValue)
    GetBackgroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS2_GetBackgroundValue)
    SetForegroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS2_SetForegroundValue)
    GetForegroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS2_GetForegroundValue)
    GetNumberOfObjects = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS2_GetNumberOfObjects)
    SetNumberOfObjects = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS2_SetNumberOfObjects)
    GetReverseOrdering = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS2_GetReverseOrdering)
    SetReverseOrdering = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS2_SetReverseOrdering)
    ReverseOrderingOn = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS2_ReverseOrderingOn)
    ReverseOrderingOff = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS2_ReverseOrderingOff)
    GetAttribute = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS2_GetAttribute)
    SetAttribute = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS2_SetAttribute)
    __swig_destroy__ = _itkBinaryShapeKeepNObjectsImageFilterPython.delete_itkBinaryShapeKeepNObjectsImageFilterIUS2
    cast = _swig_new_static_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS2_cast)

    def New(*args, **kargs):
        """New() -> itkBinaryShapeKeepNObjectsImageFilterIUS2

        Create a new object of the class itkBinaryShapeKeepNObjectsImageFilterIUS2 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkBinaryShapeKeepNObjectsImageFilterIUS2.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkBinaryShapeKeepNObjectsImageFilterIUS2.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkBinaryShapeKeepNObjectsImageFilterIUS2.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkBinaryShapeKeepNObjectsImageFilterIUS2 in _itkBinaryShapeKeepNObjectsImageFilterPython:
_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS2_swigregister(itkBinaryShapeKeepNObjectsImageFilterIUS2)
itkBinaryShapeKeepNObjectsImageFilterIUS2___New_orig__ = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS2___New_orig__
itkBinaryShapeKeepNObjectsImageFilterIUS2_cast = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS2_cast


def itkBinaryShapeKeepNObjectsImageFilterIUS3_New():
    return itkBinaryShapeKeepNObjectsImageFilterIUS3.New()

class itkBinaryShapeKeepNObjectsImageFilterIUS3(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUS3IUS3):
    r"""Proxy of C++ itkBinaryShapeKeepNObjectsImageFilterIUS3 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS3___New_orig__)
    Clone = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS3_Clone)
    SetFullyConnected = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS3_SetFullyConnected)
    GetFullyConnected = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS3_GetFullyConnected)
    FullyConnectedOn = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS3_FullyConnectedOn)
    FullyConnectedOff = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS3_FullyConnectedOff)
    InputEqualityComparableCheck = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS3_InputEqualityComparableCheck
    
    IntConvertibleToInputCheck = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS3_IntConvertibleToInputCheck
    
    InputOStreamWritableCheck = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS3_InputOStreamWritableCheck
    
    SetBackgroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS3_SetBackgroundValue)
    GetBackgroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS3_GetBackgroundValue)
    SetForegroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS3_SetForegroundValue)
    GetForegroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS3_GetForegroundValue)
    GetNumberOfObjects = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS3_GetNumberOfObjects)
    SetNumberOfObjects = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS3_SetNumberOfObjects)
    GetReverseOrdering = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS3_GetReverseOrdering)
    SetReverseOrdering = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS3_SetReverseOrdering)
    ReverseOrderingOn = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS3_ReverseOrderingOn)
    ReverseOrderingOff = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS3_ReverseOrderingOff)
    GetAttribute = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS3_GetAttribute)
    SetAttribute = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS3_SetAttribute)
    __swig_destroy__ = _itkBinaryShapeKeepNObjectsImageFilterPython.delete_itkBinaryShapeKeepNObjectsImageFilterIUS3
    cast = _swig_new_static_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS3_cast)

    def New(*args, **kargs):
        """New() -> itkBinaryShapeKeepNObjectsImageFilterIUS3

        Create a new object of the class itkBinaryShapeKeepNObjectsImageFilterIUS3 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkBinaryShapeKeepNObjectsImageFilterIUS3.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkBinaryShapeKeepNObjectsImageFilterIUS3.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkBinaryShapeKeepNObjectsImageFilterIUS3.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkBinaryShapeKeepNObjectsImageFilterIUS3 in _itkBinaryShapeKeepNObjectsImageFilterPython:
_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS3_swigregister(itkBinaryShapeKeepNObjectsImageFilterIUS3)
itkBinaryShapeKeepNObjectsImageFilterIUS3___New_orig__ = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS3___New_orig__
itkBinaryShapeKeepNObjectsImageFilterIUS3_cast = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS3_cast


def itkBinaryShapeKeepNObjectsImageFilterIUS4_New():
    return itkBinaryShapeKeepNObjectsImageFilterIUS4.New()

class itkBinaryShapeKeepNObjectsImageFilterIUS4(itk.itkImageToImageFilterAPython.itkImageToImageFilterIUS4IUS4):
    r"""Proxy of C++ itkBinaryShapeKeepNObjectsImageFilterIUS4 class."""

    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined")
    __repr__ = _swig_repr
    __New_orig__ = _swig_new_static_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS4___New_orig__)
    Clone = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS4_Clone)
    SetFullyConnected = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS4_SetFullyConnected)
    GetFullyConnected = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS4_GetFullyConnected)
    FullyConnectedOn = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS4_FullyConnectedOn)
    FullyConnectedOff = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS4_FullyConnectedOff)
    InputEqualityComparableCheck = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS4_InputEqualityComparableCheck
    
    IntConvertibleToInputCheck = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS4_IntConvertibleToInputCheck
    
    InputOStreamWritableCheck = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS4_InputOStreamWritableCheck
    
    SetBackgroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS4_SetBackgroundValue)
    GetBackgroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS4_GetBackgroundValue)
    SetForegroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS4_SetForegroundValue)
    GetForegroundValue = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS4_GetForegroundValue)
    GetNumberOfObjects = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS4_GetNumberOfObjects)
    SetNumberOfObjects = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS4_SetNumberOfObjects)
    GetReverseOrdering = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS4_GetReverseOrdering)
    SetReverseOrdering = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS4_SetReverseOrdering)
    ReverseOrderingOn = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS4_ReverseOrderingOn)
    ReverseOrderingOff = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS4_ReverseOrderingOff)
    GetAttribute = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS4_GetAttribute)
    SetAttribute = _swig_new_instance_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS4_SetAttribute)
    __swig_destroy__ = _itkBinaryShapeKeepNObjectsImageFilterPython.delete_itkBinaryShapeKeepNObjectsImageFilterIUS4
    cast = _swig_new_static_method(_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS4_cast)

    def New(*args, **kargs):
        """New() -> itkBinaryShapeKeepNObjectsImageFilterIUS4

        Create a new object of the class itkBinaryShapeKeepNObjectsImageFilterIUS4 and set the input and the parameters if some
        named or non-named arguments are passed to that method.

        New() tries to assign all the non named parameters to the input of the new objects - the
        first non named parameter in the first input, etc.

        The named parameters are used by calling the method with the same name prefixed by 'Set'.

        Ex:

          itkBinaryShapeKeepNObjectsImageFilterIUS4.New(reader, threshold=10)

        is (most of the time) equivalent to:

          obj = itkBinaryShapeKeepNObjectsImageFilterIUS4.New()
          obj.SetInput(0, reader.GetOutput())
          obj.SetThreshold(10)
        """
        obj = itkBinaryShapeKeepNObjectsImageFilterIUS4.__New_orig__()
        from itk.support import template_class
        template_class.New(obj, *args, **kargs)
        return obj
    New = staticmethod(New)


# Register itkBinaryShapeKeepNObjectsImageFilterIUS4 in _itkBinaryShapeKeepNObjectsImageFilterPython:
_itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS4_swigregister(itkBinaryShapeKeepNObjectsImageFilterIUS4)
itkBinaryShapeKeepNObjectsImageFilterIUS4___New_orig__ = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS4___New_orig__
itkBinaryShapeKeepNObjectsImageFilterIUS4_cast = _itkBinaryShapeKeepNObjectsImageFilterPython.itkBinaryShapeKeepNObjectsImageFilterIUS4_cast


from itk.support import helpers
import itk.support.types as itkt
from typing import Sequence, Tuple, Union

@helpers.accept_array_like_xarray_torch
def binary_shape_keep_n_objects_image_filter(*args: itkt.ImageLike,  fully_connected: bool=..., background_value: int=..., foreground_value: int=..., number_of_objects: int=..., reverse_ordering: bool=..., attribute: Union[str, int]=...,**kwargs)-> itkt.ImageSourceReturn:
    """Functional interface for BinaryShapeKeepNObjectsImageFilter"""
    import itk

    kwarg_typehints = { 'fully_connected':fully_connected,'background_value':background_value,'foreground_value':foreground_value,'number_of_objects':number_of_objects,'reverse_ordering':reverse_ordering,'attribute':attribute }
    specified_kwarg_typehints = { k:v for (k,v) in kwarg_typehints.items() if kwarg_typehints[k] is not ... }
    kwargs.update(specified_kwarg_typehints)


    instance = itk.BinaryShapeKeepNObjectsImageFilter.New(*args, **kwargs)

    return instance.__internal_call__()

def binary_shape_keep_n_objects_image_filter_init_docstring():
    import itk
    from itk.support import template_class

    filter_class = itk.ITKLabelMap.BinaryShapeKeepNObjectsImageFilter
    binary_shape_keep_n_objects_image_filter.process_object = filter_class
    is_template = isinstance(filter_class, template_class.itkTemplate)
    if is_template:
        filter_object = filter_class.values()[0]
    else:
        filter_object = filter_class

    binary_shape_keep_n_objects_image_filter.__doc__ = filter_object.__doc__




