import sys, os

class Error(BaseException): ...
class DatabaseError(BaseException): ...
class VPNDeteck(BaseException): ...
class ProxyAuthentication(BaseException): ...
class ProxyError(BaseException): ...
