# coding: utf-8

"""
    AtroCore REST API documentation

    This is a REST API documentation for AtroCore data platform and its modules (AtroPIM, AtroDAM and others), which is based on [OpenAPI (Swagger) Specification](https://swagger.io/specification/). You can generate your client [here](https://openapi-generator.tech/docs/generators).<br><br><h3>Video tutorials:</h3><ul><li>[How to authorize?](https://youtu.be/GWfNRvCswXg)</li><li>[How to select specific fields?](https://youtu.be/i7o0aENuyuY)</li><li>[How to filter data records?](https://youtu.be/irgWkN4wlkM)</li></ul>

    The version of the OpenAPI document: 1.6.55
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from clientapi_atrocore.api.treo_store_api import TreoStoreApi  # noqa: E501


class TestTreoStoreApi(unittest.TestCase):
    """TreoStoreApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TreoStoreApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_add_relation_for_treo_store(self) -> None:
        """Test case for add_relation_for_treo_store

        Add relation for TreoStore  # noqa: E501
        """
        pass

    def test_create_treo_store_item(self) -> None:
        """Test case for create_treo_store_item

        Create a record of the TreoStore  # noqa: E501
        """
        pass

    def test_delete_treo_store_item(self) -> None:
        """Test case for delete_treo_store_item

        Delete a record of the TreoStore  # noqa: E501
        """
        pass

    def test_follow_treo_store(self) -> None:
        """Test case for follow_treo_store

        Follow the TreoStore stream  # noqa: E501
        """
        pass

    def test_get_linked_items_for_treo_store_item(self) -> None:
        """Test case for get_linked_items_for_treo_store_item

        Returns linked entities for the TreoStore  # noqa: E501
        """
        pass

    def test_get_list_of_treo_store_items(self) -> None:
        """Test case for get_list_of_treo_store_items

        Returns a collection of TreoStore records  # noqa: E501
        """
        pass

    def test_get_treo_store_item(self) -> None:
        """Test case for get_treo_store_item

        Returns a record of the TreoStore  # noqa: E501
        """
        pass

    def test_link_treo_store(self) -> None:
        """Test case for link_treo_store

        Link TreoStore to Entities  # noqa: E501
        """
        pass

    def test_mass_delete_treo_store(self) -> None:
        """Test case for mass_delete_treo_store

        Mass delete of TreoStore data  # noqa: E501
        """
        pass

    def test_mass_update_treo_store(self) -> None:
        """Test case for mass_update_treo_store

        Mass update of TreoStore data  # noqa: E501
        """
        pass

    def test_remove_relation_for_treo_store(self) -> None:
        """Test case for remove_relation_for_treo_store

        Remove relation for TreoStore  # noqa: E501
        """
        pass

    def test_unfollow_treo_store(self) -> None:
        """Test case for unfollow_treo_store

        Unfollow the TreoStore stream  # noqa: E501
        """
        pass

    def test_unlink_treo_store(self) -> None:
        """Test case for unlink_treo_store

        Unlink TreoStore from Entities  # noqa: E501
        """
        pass

    def test_update_treo_store_item(self) -> None:
        """Test case for update_treo_store_item

        Update a record of the TreoStore  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
