
'''
from CYTE.STRUCTS.SCAN.NAMES_NO_DUPLICATES import STRUCTS_NAMES_NO_DUPLICATES
STRUCTS = STRUCTS_NAMES_NO_DUPLICATES ("VITAMIN B")
'''

import CYTE.STRUCTS.SCAN as STRUCT_SCAN

def STRUCTS_NAMES_NO_DUPLICATES (CONTAINS):
	CONTAINS = CONTAINS.upper ()

	NAMES = []

	def FOR_EACH (STRUCT):
		STRUCT_NAMES = STRUCT ["NAMES"]
			
		for STRUCT_NAME in STRUCT_NAMES:
			STRUCT_NAME = STRUCT_NAME.upper ()
		
			if (STRUCT_NAME.__contains__ (CONTAINS)):
				return True

		return False

	
	STRUCTS = STRUCT_SCAN.START (
		FOR_EACH = FOR_EACH
	)

	return STRUCTS