# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai/lzy/v1/long-running/option.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#ai/lzy/v1/long-running/option.proto\x12\tai.lzy.v1\x1a google/protobuf/descriptor.proto\"5\n\x0fOperationOption\x12\x10\n\x08metadata\x18\x01 \x01(\t\x12\x10\n\x08response\x18\x02 \x01(\t:O\n\toperation\x12\x1e.google.protobuf.MethodOptions\x18\xb6\xf8\x05 \x01(\x0b\x32\x1a.ai.lzy.v1.OperationOptionB\x17\n\x15\x61i.lzy.v1.longrunningb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.lzy.v1.long_running.option_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025ai.lzy.v1.longrunning'
  _globals['_OPERATIONOPTION']._serialized_start=84
  _globals['_OPERATIONOPTION']._serialized_end=137
# @@protoc_insertion_point(module_scope)
