

'''
	from CYTE.FOOD.USDA.FORM_1.CALC.PACKAGE_MASS import PACKAGE_MASS
	MASS = PACKAGE_MASS.PROCESS (
		PACKAGE_WEIGHT = "4 oz/113 g"
	)
'''


from .FN.INTERPRET import INTERPRET 
	

def PROCESS (
	PACKAGE_WEIGHT
):
	PACKAGE_MASS = {
		"REPORTED": PACKAGE_WEIGHT
	}
	INTERPRETED_PACKAGE_WEIGHT = INTERPRET (
		PACKAGE_WEIGHT
	)
	
	return {
		"REPORTED": PACKAGE_WEIGHT,
		"SYSTEM INTERNATIONAL": [
			INTERPRETED_PACKAGE_WEIGHT [ "GRAMS" ], 
			"g"
		]
	}