from _typeshed import Incomplete
from conan.tools.gnu.gnudeps_flags import GnuDepsFlags as GnuDepsFlags
from conan.tools.meson.helpers import to_meson_value as to_meson_value

class MesonDeps:
    filename: str
    _meson_file_template: Incomplete
    _conanfile: Incomplete
    _ordered_deps: Incomplete
    c_args: Incomplete
    c_link_args: Incomplete
    cpp_args: Incomplete
    cpp_link_args: Incomplete
    def __init__(self, conanfile) -> None: ...
    @property
    def ordered_deps(self): ...
    def _get_cpp_info(self): ...
    def _rpaths_flags(self): ...
    def get_gnu_flags(self): ...
    def _context(self): ...
    def _content(self): ...
    def generate(self) -> None: ...
