from _typeshed import Incomplete
from conan.tools.files.files import load_toolchain_args as load_toolchain_args

class Bazel:
    _conanfile: Incomplete
    _namespace: Incomplete
    def __init__(self, conanfile, namespace: Incomplete | None = ...) -> None: ...
    def configure(self, args: Incomplete | None = ...) -> None: ...
    def build(self, args: Incomplete | None = ..., label: Incomplete | None = ...) -> None: ...
    _bazel_config: Incomplete
    _bazelrc_path: Incomplete
    def _get_bazel_project_configuration(self) -> None: ...
