from _typeshed import Incomplete
from conan.tools.cmake.layout import get_build_folder_custom_vars as get_build_folder_custom_vars
from conan.tools.cmake.utils import is_multi_configuration as is_multi_configuration
from conan.tools.microsoft import is_msvc as is_msvc

def _build_and_test_preset_fields(conanfile, multiconfig): ...
def _build_and_test_preset_name(conanfile): ...
def _configure_preset_name(conanfile, multiconfig): ...
def _configure_preset(conanfile, generator, cache_variables, toolchain_file, multiconfig): ...
def _insert_preset(data, preset_name, preset) -> None: ...
def _forced_schema_2(conanfile): ...
def _schema_version(conanfile, default): ...
def _contents(conanfile, toolchain_file, cache_variables, generator): ...
def write_cmake_presets(conanfile, toolchain_file, generator, cache_variables, user_presets_path: Incomplete | None = ...) -> None: ...
def _save_cmake_user_presets(conanfile, preset_path, user_presets_path) -> None: ...
def _get_already_existing_preset_index(name, presets): ...
def _append_user_preset_path(conanfile, data, preset_path): ...
def load_cmake_presets(folder): ...
