from _typeshed import Incomplete
from conan.tools._compilers import build_type_flags as build_type_flags, build_type_link_flags as build_type_link_flags, cppstd_flag as cppstd_flag
from conan.tools.env import Environment as Environment
from conan.tools.microsoft.visual import VCVars as VCVars, msvc_runtime_flag as msvc_runtime_flag

class NMakeToolchain:
    _conanfile: Incomplete
    extra_cflags: Incomplete
    extra_cxxflags: Incomplete
    extra_ldflags: Incomplete
    extra_defines: Incomplete
    def __init__(self, conanfile) -> None: ...
    def _format_options(self, options): ...
    def _format_defines(self, defines): ...
    @property
    def _cl(self): ...
    @property
    def _link(self): ...
    def environment(self): ...
    def vars(self): ...
    def generate(self, env: Incomplete | None = ..., scope: str = ...) -> None: ...
