from _typeshed import Incomplete
from conan.tools.intel.intel_cc import IntelCC as IntelCC

CONAN_VCVARS_FILE: str

def check_min_vs(conanfile, version, raise_invalid: bool = ...): ...
def msvc_version_to_vs_ide_version(version): ...
def msvc_version_to_toolset_version(version): ...

class VCVars:
    _conanfile: Incomplete
    def __init__(self, conanfile) -> None: ...
    def generate(self, scope: str = ...) -> None: ...

def vs_ide_version(conanfile): ...
def msvc_runtime_flag(conanfile): ...
def vcvars_command(version, architecture: Incomplete | None = ..., platform_type: Incomplete | None = ..., winsdk_version: Incomplete | None = ..., vcvars_ver: Incomplete | None = ..., start_dir_cd: bool = ..., vs_install_path: Incomplete | None = ...): ...
def _vcvars_path(version, vs_install_path): ...
def vcvars_arch(conanfile): ...
def _vcvars_vers(conanfile, compiler, vs_version): ...
def is_msvc(conanfile, build_context: bool = ...): ...
def is_msvc_static_runtime(conanfile): ...
def msvs_toolset(conanfile): ...
