
'''
import CYTE.STRUCTS.DB.ACCESS as ACCESS
from CYTE.STRUCTS.SCAN.NAMES.CONTAIN import STRUCTS_NAMES_CONTAIN
STRUCTS = STRUCTS_NAMES_CONTAIN (
	ACCESS.DB (),
	"VITAMIN B"
)
'''

import CYTE.STRUCTS.SCAN as STRUCT_SCAN

def STRUCTS_NAMES_CONTAIN (
	STRUCTS_DB,
	CONTAINS
):
	CONTAINS = CONTAINS.upper ()

	def FOR_EACH (STRUCT):
		STRUCT_NAMES = STRUCT ["NAMES"]
			
		for STRUCT_NAME in STRUCT_NAMES:
			STRUCT_NAME = STRUCT_NAME.upper ()
		
			if (STRUCT_NAME.__contains__ (CONTAINS)):
				#Q = Query ()
				#EL = db.get (Q.REGION == STRUCT ["REGION"])
				
				return True

		return False
	
	STRUCTS = STRUCT_SCAN.START (
		FOR_EACH = FOR_EACH
	)


	return STRUCTS