from _typeshed import Incomplete

def is_apple_os(conanfile): ...
def to_apple_arch(conanfile): ...
def _guess_apple_sdk_name(os_, arch): ...
def apple_sdk_name(settings): ...
def apple_min_version_flag(conanfile): ...
def apple_sdk_path(conanfile): ...

class XCRun:
    settings: Incomplete
    sdk: Incomplete
    def __init__(self, conanfile, sdk: Incomplete | None = ..., use_settings_target: bool = ...) -> None: ...
    def _invoke(self, args): ...
    def find(self, tool): ...
    @property
    def sdk_path(self): ...
    @property
    def sdk_version(self): ...
    @property
    def sdk_platform_path(self): ...
    @property
    def sdk_platform_version(self): ...
    @property
    def cc(self): ...
    @property
    def cxx(self): ...
    @property
    def ar(self): ...
    @property
    def ranlib(self): ...
    @property
    def strip(self): ...
    @property
    def libtool(self): ...

def _get_dylib_install_name(path_to_dylib): ...
def fix_apple_shared_install_name(conanfile): ...
