from _typeshed import Incomplete
from conan.tools._check_build_profile import check_using_build_profile as check_using_build_profile

GLOBAL_XCCONFIG_TEMPLATE: Incomplete
GLOBAL_XCCONFIG_FILENAME: str

def _format_name(name): ...
def _xcconfig_settings_filename(settings): ...
def _xcconfig_conditional(settings): ...
def _add_includes_to_file_or_create(filename, template, files_to_include): ...

class XcodeDeps:
    general_name: str
    _conf_xconfig: Incomplete
    _dep_xconfig: Incomplete
    _all_xconfig: Incomplete
    _pkg_xconfig: Incomplete
    _conanfile: Incomplete
    configuration: Incomplete
    architecture: Incomplete
    os_version: Incomplete
    sdk: Incomplete
    sdk_version: Incomplete
    def __init__(self, conanfile) -> None: ...
    def generate(self) -> None: ...
    def _conf_xconfig_file(self, pkg_name, comp_name, package_folder, transitive_cpp_infos): ...
    def _dep_xconfig_file(self, pkg_name, comp_name, name_general, dep_xconfig_filename, reqs): ...
    def _all_xconfig_file(self, deps): ...
    def _pkg_xconfig_file(self, components): ...
    @property
    def _global_xconfig_content(self): ...
    def get_content_for_component(self, pkg_name, component_name, package_folder, transitive_internal, transitive_external): ...
    def _content(self): ...
